# -*- coding: utf-8 -*-
"""prueba_streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/prueba-streamlit-433b5ac1-3615-4bc8-9ca3-76ad59c8114d.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250214/auto/storage/goog4_request%26X-Goog-Date%3D20250214T202811Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7a531c5a9b5560dc705a4cdeb20c6270c49654260ee45ab4209566b0be012062f24690f2752b0463f3046aa9219d0cb71b0e2e5fdf7b0ec8d4f6804122cdcaa885f1c79fe2991c30c2ed4a1c21137d80a1eeb8e04027a0dedbfc3e9f05613d3223af66a534e0735df826e8a71b33a02e32e8f119e72c71590c1ef1f03c81cba3d70c99fa0a924fefbf760c9004899b42ce953585d658611e9bf6dd3434d5c6b5e4e768faf9e8dce7c0487ce33ca73e230dfdec2b48a2091d9ef21128fdbdb955781d5261267d695e2d339fdb0293edcbe5e92605be50e625c24df5dccf67a912b956224f9920d47cabb3cc453482fb3706b88eb0a7c27bf99f6dba0dfb4aba96
"""

# Crear un cuadro de texto
nombre = st.text_input('¿Cuál es tu nombre?')

# Crear un control deslizante
edad = st.slider('¿Cuál es tu edad?', 0, 100, 25)

# Mostrar la información
if nombre:
    st.write(f'Hola, {nombre}. Tienes {edad} años.')

# Botón para mostrar un mensaje
if st.button('Saludar'):
    st.success(f'¡Saludos, {nombre}!')

# Mostrar gráficos simples
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)

fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_title('Gráfico de Seno')

st.pyplot(fig)